# Generated by Django 4.2.16 on 2024-09-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agndame_app', '0003_appointment_email_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='email_client',
            new_name='email',
        ),
    ]
